version: '3'

services:

  # MariaDB database for auth, storing information about labs, etc

  database:
    build:
      context: docker/database
    image: wshand/lawliet-database:latest
    container_name: lawliet-database
    volumes:
      - dbvol:/var/lib/mysql:rw
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    env_file:
      - .env
    networks:
      - labnet
    ports:
      - "5432:5432"

  # Webserver which serves as the main interface for the site

  webserver:
    build:
      context: .
      dockerfile: docker/webserver/Dockerfile
    image: wshand/lawliet-webserver:latest
    container_name: lawliet-webserver
    volumes:
      - ./src:/var/www/src:ro
    environment:
      STATIC_ROOT: "/var/www/static"
      DATABASE_ENGINE: mysql
    env_file:
      - .env
    networks:
      - labnet
    depends_on:
      - database

  # Apache Guacamole

  guacd:
    image: guacamole/guacd:latest
    container_name: lawliet-guacd
    networks:
      - labnet

  guacamole:
    build:
      context: docker/guacamole
    image: wshand/lawliet-guacamole:latest
    container_name: lawliet-guacamole
    env_file:
      - .env
    environment:
      GUACAMOLE_HOME: "/etc/guacamole"
      GUACD_HOSTNAME: lawliet-guacd
      GUACD_PORT: 4822
      MYSQL_HOSTNAME: lawliet-database
    ports:
      - "8080:8080"
    networks:
      - labnet
    depends_on:
      - database
      - guacd

  # Nginx proxy between the webserver and the rest of the world

  proxy:
    build:
      context: docker/proxy
    image: wshand/lawliet-proxy:latest
    container_name: lawliet-proxy
    env_file:
      - .env
    volumes:
      - tls:/etc/letsencrypt:rw
    networks:
      - labnet
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webserver
      - guacamole

  # SSH server accessible over Guacamole for testing purposes

  lawliet-ssh:
    build:
      context: docker/ssh
      args:
        FROM_IMAGE: "debian:buster-slim"
    container_name: lawliet-ssh
    image: wshand/lawliet-ssh
    networks:
      - labnet
    depends_on:
      - guacamole

networks:
  labnet:

volumes:
  tls:
  dbvol:
