version: '3'

services:

  database:
    build:
      context: deploy_tools/db
    image: wshand/lawliet-dashboard-database:latest
    volumes:
      - mysql-database:/var/lib/mysql:rw
    env_file:
      - .env
    ports:
      - "5432:5432"

  webserver:
    build:
      context: .
      dockerfile: deploy_tools/webserver/Dockerfile
    image: wshand/lawliet-dashboard-webserver:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - database

  proxy:
    build:
      context: deploy_tools/proxy
    image: wshand/lawliet-dashboard-proxy:latest
    env_file:
      - .env
    volumes:
      - tls:/etc/letsencrypt:rw
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webserver

volumes:
  tls:
  mysql-database:
