# Generated by Django 3.0.5 on 2020-04-15 03:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("url", models.URLField(default=None)),
                ("protocol", models.CharField(max_length=32)),
                ("port", models.PositiveIntegerField()),
            ],
        ),
    ]
