# Generated by Django 3.0.3 on 2020-04-29 20:52

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30, unique=True)),
                ("description", models.CharField(max_length=1000)),
                ("category", models.CharField(max_length=50)),
                ("url", models.CharField(default=None, max_length=200)),
                ("protocol", models.CharField(max_length=32)),
                ("port", models.PositiveIntegerField()),
                (
                    "date_uploaded",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
