# Generated by Django 3.0.1 on 2020-02-04 16:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabEnvironment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(default=None, max_length=30)),
                ("description", models.CharField(max_length=1000)),
                ("url", models.URLField(default=None, max_length=100)),
                ("header_image", models.ImageField(upload_to="labs/img")),
                ("has_web_interface", models.BooleanField(default=True)),
            ],
        )
    ]
