# Generated by Django 3.0.3 on 2020-02-24 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="labenvironment", name="header_image",),
    ]
