apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawliet-guacamole-dply
  labels:
    app: lawliet-guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lawliet-guacamole
  template:
    metadata:
      labels:
        app: lawliet-guacamole
    spec:
      containers:
        - name: lawliet-guacamole
          image: wshand/lawliet-guacamole:latest
          imagePullPolicy: Always
          env:
            - name: "GUACAMOLE_HOME"
              value: "/etc/guacamole"
            - name: "GUACD_HOSTNAME"
              value: "lawliet-guacd"
            - name: "GUACD_PORT"
              value: "4822"
            - name: "MYSQL_HOSTNAME"
              value: "lawliet-database"
          envFrom:
            - secretRef:
                name: dashboard-secrets
          ports:
            - containerPort: 8080
              protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lawliet-guacd-dply
  labels:
    app: lawliet-guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lawliet-guacamole
  template:
    metadata:
      labels:
        app: lawliet-guacamole
    spec:
      containers:
        - name: lawliet-guacd
          image: guacamole/guacd:latest
          ports:
            - containerPort: 4822
              protocol: TCP

---

### SERVICES

apiVersion: v1
kind: Service
metadata:
  name: lawliet-guacamole
apiVersion: v1
kind: Service
metadata:
  name: lawliet-guacamole
spec:
  selector:
    app: lawliet-guacamole
  ports:
    - name: guacamole
      port: 8080
      targetPort: 8080
      protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: lawliet-guacd
apiVersion: v1
kind: Service
metadata:
  name: lawliet-guacd
spec:
  selector:
    app: lawliet-guacd
  ports:
    - name: guacamole
      port: 4822
      targetPort: 4822
      protocol: TCP

